---
kind: VirtualService
apiVersion: networking.istio.io/v1alpha3
metadata:
  name: helloworld-vs
spec:
  hosts:
    - "*" #Copy the value in the Gateway hosts
  gateways:
    - helloworld/helloworld-gw
  http:
    - route:
        - destination:
            host: helloworld  #The Service DNS name
